version: '3'
services:
  radarr:
    container_name: radarr-2
    image: linuxserver/radarr
    ports:
      - "7878:7878"
    volumes:
      - /mnt/user/Movies:/movies
      - /mnt/user/Downloads:/data
      - /mnt/user/appdata/arr-stack/radarr-data:/config:rw
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    restart: always
    networks:
      - arrnet  
  sonarr:
    container_name: sonarr-2
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    volumes:
      - /mnt/user/TV/:/tv
      - /mnt/user/Anime:/Anime
      - /mnt/user/Downloads:/data
      - /mnt/user/appdata/arr-stack/sonarr-data:/config:rw
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    restart: always
    networks:
      - arrnet
  lidarr:
    container_name: lidarr-2
    image: linuxserver/lidarr
    ports:
      - "8686:8686"
    volumes:
      - /mnt/user/Music:/media
      - /mnt/user/Downloads:/data
      - /mnt/user/appdata/arr-stack/lidarr-data:/config:rw
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    restart: always
    networks:
      - arrnet
  overseerr:
    container_name: overseerr-2
    image: linuxserver/overseerr
    ports:
      - "5055:5055"
    volumes:
      - /mnt/user/appdata/arr-stack/overseerr-data:/config:rw
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    restart: always
    networks:
      - arrnet
  prowlarr:
    container_name: prowlarr-2
    image: linuxserver/prowlarr:nightly
    ports:
      - "9696:9696"
    volumes:
      - /mnt/user/appdata/arr-stack/prowlarr-data:/config:rw
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    restart: always
    networks:
      - arrnet

networks:
  arrnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.200.0/28
          gateway: 172.100.200.1
