version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    ports:
      - 5000:80/TCP
      - 5001:443/tcp
    volumes:
      - vaultwarden:/data
    environment:
      - SIGNUPS_ALLOWED=true
      - INVITATIONS_ALLOWED=false
      - ADMIN_TOKEN=$ADMIN
      - YUBICO_CLIENT_ID=$YUBI_CLIENT
      - YUBICO_SECRET_KEY=$YUBI_SECRET
      - WEBSOCKET_ENABLED=ture
    restart: always
  backup:
    image: bruceforce/vaultwarden-backup
    container_name: vaultwarden-backup
    volumes:
      - vaultwarden:/data:ro
      - /home/tgoodspeed/vaultwarden-backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TIMESTAMP=ture
      - DELETE_AFTER=30
      - CRON_TIME="*/15 * * * *"
      - BACKUP_ADD_CONFIG_JSON=true
      - BACKUP_ADD_DATABASE=true
      - BACKUP_ADD_ATTACHMENTS=true
      - BACKUP_ADD_RSA_KEY=true
volumes:
  vaultwarden:
    external: false
